### PR TITLE
HW-345:Fixed peoples tab markup and styling

### PR DESCRIPTION
**Pull request by mukeshcompucorp**
**Before**
before

**After**
after

### CODE REVIEW

**Comment by colemanw** [comment]
@mukeshcompucorp I don't understand why you don't want the greyed-out pager arrows to be visible. On a single page like this one (which will be very common), it won't be obvious that it's even a pager (it just looks like the number 1 is printed on the screen for no reason).

**Comment by mukeshcompucorp** [comment]
@colemanw that is what our design suggests to hide the disabled section. I understand your concern but, I will confirm this with @guanhuan for this.

**Comment by guanhuan** [comment]
@colemanw @mukeshcompucorp I am happy with how CiviCRM handles pagers currently (just need to append page number links to it). That is to not show pager when there is only one page. We might need to revisit both the markups and stylings.

**Comment by mukeshcompucorp** [comment]
@guanhuan so, we keep it disabled page navigation in grey color or remove it? can you confirm that with Jon?

**Comment by mukeshcompucorp** [comment]
@colemanw https://projects.invisionapp.com/d/main#/console/9877377/211046155/preview
Can you go here add check "Page 1 of 13" and add that on the page. 
Also can you hide pager when we have only 1 page?

Let me know once you do that, I can style it on whatever level needed afterwards

**Comment by colemanw** [comment]
@mukeshcompucorp done.

**Pull request merged**
