### PR TITLE
Recent cases dashboard dashlet

### PR DESCRIPTION
**Pull request by colemanw**

### CODE REVIEW

**Comment by colemanw** [comment]
@mukeshcompucorp this will need styling FYI:

dashletrecentcasesunstyled

**Comment by mukeshcompucorp** [comment]
@colemanw ,
I get the error as below
`
{error_code: 0, entity: "Case", action: "getdetails", is_error: 1, error_message: "Unknown field specified for sort. Cannot order by 'modified_date DESC'"}
`

I am designing with sort subject for now but, can you let me know what other things I need to update in order to get this right

**Comment by mukeshcompucorp** [comment]
@colemanw Also, we need full section of civicrm/case/a/#/case/list for the table in recent cases with all filter which does not seem here. For doing design I will need that sections as well. Can you please look into this and update the code?

**Comment by colemanw** [comment]
@mukeshcompucorp `modified_date` was recently added to civicrm core. You will need to either update your sandbox site and run the upgrader, or else just rebuild it.

**Comment by colemanw** [comment]
IMO we should not be adding the filters to the recent cases dashlet. If people want filters they can go to the case/list screen. The filter is already set in this dashlet to "cases most recently modified".

**Comment by mukeshcompucorp** [comment]
@colemanw thanks I will run upgrader and get the latest one.

**Comment by mukeshcompucorp** [comment]
@guanhuan can you ask Jon to have new design markup in the case we do not need filters.

Also, should it have all columns that we have on the list page? Please confirm and I will start designing it.

**Comment by guanhuan** [comment]
@mukeshcompucorp will ask Jon to update the design for this. Can we also hide the arrow next to the Last updated column heading via css?

**Pull request merged**
