### PR TITLE
HW-341: Styling UI snaggin on summary page

### PR DESCRIPTION
**Pull request by mukeshcompucorp**
**Before:**
before

**After:**
after

### CODE REVIEW

**Comment by guanhuan** [comment]
@mukeshcompucorp looks great to me

**Comment by colemanw** [comment]
@guanhuan I'm confused - I thought the first custom field was supposed to be up top. Why was it moved?

**Comment by guanhuan** [comment]
@colemanw sorry I missed that. I will take it internally to resolve before pass it to you again.

**Comment by JonScreat** [comment]
@mukeshcompucorp We need to move the first custom fields set back to the top again. This is a deviation from the mockups which I was not aware of. Apologies for any confusion.

**Pull request merged**
