### PR TITLE
HW-356: Changed layout of case search page

### PR DESCRIPTION
**Pull request by mihaelmladenov**
Before:
before

After:
after5

### CODE REVIEW

**Comment by colemanw** [comment]
Hmm, the 2 checkboxes on the right seem out-of-place.

**Comment by mihaelmladenov** [comment]
Adjusted checkboxes to be vertically centered:
after2

**Comment by mihaelmladenov** [comment]
Spacing of date fields fixed.
after3

**Comment by mihaelmladenov** [comment]
Changed implemented. Please see attached screenshot.
after5

**Comment by colemanw** [comment]
When I say they look out-of-place, I mean that they are the only 2 items in the 2nd column of the layout, and they don't even start on the top line. Which makes them look like they are somehow related to the fields to their left. Which they aren't (Client Name or Email shouldn't logically be grouped with Deleted Cases).
If you're going to do a 1-column layout, then I think those two fields should be in column 1.
If you're going to do a 2-column layout, then the 2nd column needs to be balanced with the first.

**Comment by guanhuan** [comment]
@colemanw I think "Only my cases" is supposed to be a part of the "Case Manager" field (I know the y might physically be two). Thus I think they should be column one but needs to be on the same row still. We can argue about the "Deleted Cases" though. cc @mihaelmladenov

**Comment by colemanw** [comment]
You're right, I hadn't noticed that the "Me" checkbox was renamed to "Only My Cases" - yes, ticking that populates the field to the left with the current user.

I still prefer 2 columns - there's a lot of wasted space on the right. And I'm pretty sure if you are using standard bootstrap grid css for the columns then they will collapse to 1 for smaller screens.

**Comment by mihaelmladenov** [comment]
So, just to confirm, you emanating to have two columns with each column 50% the width of the screen. And then in these two columns we distribute the fields. This would mean I  the second column we do not have the checkboxes, but some of the fields?

**Comment by colemanw** [comment]
Yes, and that would be consistent with how custom fields are laid out too. If you add some case custom fields to your CiviCRM install you can see those fields also appear in that search form.

**Comment by guanhuan** [comment]
Our designer Jon is suggesting one column make it easier for users to scan through and find the field they want to filter quickly without going back and forth. Let's move design discussions onto invision so Jon can take a part of the decision. https://projects.invisionapp.com/d/main#/console/9877377/228539312/preview

@colemanw please leave a comment on the page and we can discuss and decide if you think change of design is required.

**Comment by colemanw** [comment]
Ok comment added.

For this PR, I do suggest you add at least 2 sets of custom fields with at least 2 searchable fields in each set to get a feel for what the layout will look like with those present and include them in your screenshots. Currently the template lays the sets side-by-side. I'm actually leaning toward having each set take up the full-width and having 2 columns of fields per set, but this is what it looks like currently:
customfieldsinsearch

**Comment by colemanw** [comment]
@mihaelmladenov @guanhuan I'm merging this so it doesn't get stale. But the custom fields on the form need work too.

**Pull request merged**
