### PR TITLE
HW-366: Fixed activity feed control and filters

### PR DESCRIPTION
**Pull request by mukeshcompucorp**
**Before:**
before

**After:**
after

**Note:**
This resolves only Point 1 of Ticket: Feed filters & config (top part of a feed that allows you to add/remove filters and change display settings)

### CODE REVIEW

**Comment by colemanw** [comment]
@mukeshcompucorp  changing "Category: All" to "View All" makes it much less clear what that selector does.

**Comment by mukeshcompucorp** [comment]
@guanhuan Can you please confirm above what we want to keep in this, as per design or as per @colemanw is suggesting? I think what @colemanw says seems valid to me.

**Comment by guanhuan** [comment]
@mukeshcompucorp 
See A/C #10 in https://issues.civicrm.org/jira/browse/CRM-20096
Let's change both here and files tab to say "All Activity Categories" by default

**Comment by mukeshcompucorp** [comment]
@colemanw Please review last commit as per comments of @guanhuan

**Comment by guanhuan** [comment]
Looks good to me

**Comment by colemanw** [comment]
@mukeshcompucorp - general note - you can avoid adding these annoying merge commits to a PR by doing

    git pull --rebase origin master
    git push -f

**Pull request merged**
