### PR TITLE
ts() > E::ts()

### PR DESCRIPTION
**Pull request by UshaMakoa**
This doesn't solve the problem that several .html pages (for example Dashboard) with ts() inside doesn't translate (and we don't even see the strings in Transifex).

### CODE REVIEW

**Comment by colemanw** [comment]
Thanks for the PR @UshaMakoa.
I don't see `use` statements at the tops of these files, which would mean `E` would be undefined causing a crash.

**Comment by UshaMakoa** [comment]
I made the correction, can you check please?
Have you any answer regarding the dashboard.html and the strings that aren't translated?

**Comment by colemanw** [comment]
Ok this looks good now.

**Comment by colemanw** [comment]
I don't see any apparent reason why the html files would fail to be translated. `ts()` appears to be working in the templates.

**Comment by demeritcowboy** [comment]
In chat in the translation channel our current theory is that it's not so much `ts` isn't working as that this extension isn't in-app, and so by policy its strings don't appear in transifex. (Unconfirmed.)

**Pull request merged**
